// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STB.SmartCard.Infrastructure.DataBaseContext;

#nullable disable

namespace STB.SmartCard.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250724162222_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Carte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("EtatCarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomPorteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PlafondPaiement")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondPaiementMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondRetrait")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlafondRetraitMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TypeCarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompteId");

                    b.ToTable("Cartes");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Compte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumCompte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Solde")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompteDestinataire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NomBanque")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePaiement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeRetrait")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarteId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Carte", b =>
                {
                    b.HasOne("STB.SmartCard.Domain.Entities.Compte", "Compte")
                        .WithMany("Cartes")
                        .HasForeignKey("CompteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compte");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Compte", b =>
                {
                    b.HasOne("STB.SmartCard.Domain.Entities.Client", "Client")
                        .WithMany("Comptes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("STB.SmartCard.Domain.Entities.Carte", "Carte")
                        .WithMany("Transactions")
                        .HasForeignKey("CarteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carte");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Carte", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Client", b =>
                {
                    b.Navigation("Comptes");
                });

            modelBuilder.Entity("STB.SmartCard.Domain.Entities.Compte", b =>
                {
                    b.Navigation("Cartes");
                });
#pragma warning restore 612, 618
        }
    }
}
